Controller Input
CaptainStack/LordsOfTheClash pull request #43
Opened 2020-04-01 04:44 UTC by FakeBrett

Adds support for Xbox controllers on Windows. The most significant change is that we are now creating an in-game cursor rather than using the OS' cursor. This allows the controller's analog sticks to move the in-game cursor. The big downside to this is that the player currently can't select their cards by clicking on them in-game (must use number keys or controller bumpers).

-Made additions to ApplicationStateManager
-Added scripts: CursorScript and HoverSelect
-Made changes to Unity Input Manager settings
-Fixed bug where the player could use abilities while the game was paused. Done using the variable pauseFix in ApplicationStateManager. (This bug was important to fix for using a controller with the pause menu).
-Currently selected card in hand is now highlighted.
-Menu buttons now become selected when the mouse hovers over them. Whichever menu button is selected will appear highlighted.

2020-04-01 04:56 UTC, CaptainStack commented
Pro tip - Github uses a markup language called "markdown" that is essentially a simplified more readable HTML. If you use an asterisk * you can get nicely formatted bulleted lists like so:

* First item
* Second item

Lots of other neat tricks too like using backticks ` to designate code like so `code` or

```
code
```

2020-04-01 04:58 UTC, CaptainStack commented
How much work do you think it would be to get the UI buttons working with the cursor? I'd rather not check in a regression.

2020-04-01 06:59 UTC, FakeBrett commented
I think I'll just have to attach colliders to the buttons and the cursor. The main problem is the script that creates the cursor is attached to the ApplicationStateManager. I will probably have to move the cursor script to a separate object so I can attach the collider, which will then require some coding reworking, but I don't think it should be too bad. I'm not sure I've attached colliders to buttons before, but I think it can be done.

*test 1
*test 2
`This is very cool, thank you!`
```
I'm great at underestimating coding problems.
I'll let you know if I fall down a dark path.
```

2020-04-01 23:21 UTC, FakeBrett commented
I just pushed an update to this branch that makes it so the player can select cards by clicking on them like they used to.

* Second test 1
* Second test 2

2020-04-01 23:47 UTC, CaptainStack requested changes
You will need to merge master into your branch to get Chris's changes before you can merge this back into master. Otherwise this looks pretty good to me. I did leave a couple other small comments.

2020-04-01 23:47 UTC, CaptainStack commented on Assets/Scripts/ApplicationStateManager.cs
> +            pauseFix = 0;
Slightly odd variable name. I'm not quite sure what it does. Since it only ever seems to be 0 or 1 why not have it be a bool?

2020-04-01 23:47 UTC, CaptainStack commented on Assets/Scripts/PlayerScripts/CursorScript.cs
> +       // this.gameObject.AddComponent<BoxCollider2D>();
Remove

2020-04-02 00:44 UTC, FakeBrett commented on Assets/Scripts/ApplicationStateManager.cs
> +            pauseFix = 0;
It makes it so pressing 'A' to resume in the pause menu won't also cast your spell right after. I'll change it to a boolean for sure.

2020-04-04 19:32 UTC, closed without merging